[build_system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "ephysanalysis"
version = "0.1.9"
dependencies = [
    "numpy",
    "pyqt5",
    "statmodels",
    "scipy",
    "scikit-learn",
    "matplotlib",
    "qdarkstyle",
    "pyqtgraph",
    "pandas",
    "yaml",
    "bottleneck",
]
requires-pyton = ">=3.9"
license = {text = "BSD 3-Clause License"}
